language: php
php:
    - 7.4
services:
    - mysql
before_install:
    - composer self-update
install: composer install --dev
before_script:
    - mysql -u root -e 'create database activecollab_jobs_queue_test'
script: php vendor/bin/phpunit
