dist: trusty
sudo: required
language: php
php:
  - 5.6
  - '7'
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
mysql:
  database: activecollab_jobs_queue_test
  username: root
  encoding: utf8mb4
install: composer install --dev
before_script:
  - mysql - root -e 'create database if not exists activecollab_jobs_queue_test;'
script: phpunit -c test/phpunit.xml
